---
- name: create network directory
  file:
    path: "{{ network_dir }}"
    state: directory

- name: Copy "{{ network }}" YAML files
  template:
    src: "{{ item }}"
    dest: "{{ network_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - ../templates/{{ network }}*.j2

- name: check "{{ network }}" daemonset is working
  shell: kubectl --kubeconfig={{ kubeadm_config }} get ds --all-namespaces | grep {{ network }}
  delegate_to: "{{ groups['all'][0] }}"
  run_once: true
  register: check_net
  ignore_errors: true
  changed_when: false

- name: create "{{ network }}" network daemonset
  when: check_net is failed
  command: kubectl apply --kubeconfig={{ kubeadm_config }} -f {{ network_dir }}/
  delegate_to: "{{ groups['all'][0] }}"
  run_once: true
