---
- name: reset kubernetes component
  shell: |
    kubeadm reset --force
  register: reset_cluster

- name: init kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --control-plane-endpoint {{ end_point }} --service-cidr {{ service_cidr }} --kubernetes-version {{ kube_version }} \
    --pod-network-cidr {{ pod_network_cidr }} --apiserver-advertise-address {{ master_ip }}
  register: init_cluster

- debug:
    var: init_cluster.stdout_lines

- name: create kubernetes config directory
  file:
    path: "/root/.kube/"
    state: directory

- name: copy admin.config to home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadm_config }}"
    dest: "/root/.kube/config"
    owner: "{{ k8s_user | default(ansible_user_id) }}"
    group: "{{ k8s_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true